default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: ofxaddons

test:
  <<: *default
  database: ofxaddons_test

production:
  <<: *default
  database: ofxaddons
