# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# NOTE: these keys are not used in production - they are set from environment variables defined in /etc/environment

development:
  secret_key_base: 93958304c0eedc68225b399c88fde5741604a5e8c2a1c56d8e806afc765f46399daeab821c6b3464c7cf1eb44cb817256d469daf8ea70f0fef66267dde1bc67d

test:
  secret_key_base: 4f809ce27fd91c53321a77d7b672b075ebfc1fc3516da3cecfa8b57e89443f9bb0478306411c785c60bbed2b314b20e7b9f8d53b1203b93ddacdc0cf711704df

production:
  secret_key_base: 93958304c0eedc68225b399c88fde5741604a5e8c2a1c56d8e806afc765f46399daeab821c6b3464c7cf1eb44cb817256d469daf8ea70f0fef66267dde1bc67d
